tasks:
  - id: "TA05"
    name: "タスク管理システムの実装"
    status: "completed"
    created_at: "2025-03-18"
    updated_at: "2025-03-18"
    description: "YAMLベースのタスク管理システムを実装する"
    concerns: "パフォーマンスとエラー処理の最適化が必要"
  - id: "TA11"
    name: "プロジェクト管理システムの開発"
    status: "in_progress"
    created_at: "2025-03-18"
    updated_at: "2025-03-18"
    description: "プロジェクト全体の管理システムを開発する"
    concerns: "スケジュール管理と進捗の可視化が重要"
  - id: "TA12"
    name: "データベース設計"
    status: "not_started"
    created_at: "2025-03-18"
    updated_at: "2025-03-18"
    parent: "TA11"
    description: "プロジェクト管理用のデータベースを設計する"
    concerns: "スケーラビリティを考慮した設計が必要"
  - id: "TA13"
    name: "フロントエンド実装"
    status: "not_started"
    created_at: "2025-03-18"
    updated_at: "2025-03-18"
    parent: "TA11"
    description: "プロジェクト管理システムのフロントエンドを実装する"
    concerns: "ユーザビリティを重視したUI設計"
  - id: "TA14"
    name: "データモデル設計"
    status: "not_started"
    created_at: "2025-03-18"
    updated_at: "2025-03-18"
    parent: "TA12"
    description: "データベースのモデル設計を行う"
    concerns: "正規化とパフォーマンスのバランスを考慮"
  - id: "TA15"
    name: "テスト用タスク"
    status: "not_started"
    created_at: "2025-03-18"
    updated_at: "2025-03-18"
    description: "テスト用のタスクです"
    concerns: "特になし"
  - id: "TA16"
    name: "プロジェクトXの開発"
    status: "in_progress"
    created_at: "2025-03-18"
    updated_at: "2025-03-18"
    description: "新規Webアプリケーションの開発プロジェクト"
    concerns: "スケジュール管理と品質管理が重要"
  - id: "TA17"
    name: "バックエンド開発"
    status: "not_started"
    created_at: "2025-03-18"
    updated_at: "2025-03-18"
    parent: "TA16"
    description: "APIとデータベースの実装"
    concerns: "セキュリティ対策の徹底"
  - id: "TA18"
    name: "フロントエンド開発"
    status: "not_started"
    created_at: "2025-03-18"
    updated_at: "2025-03-18"
    parent: "TA16"
    description: "ユーザーインターフェースの実装"
    concerns: "レスポンシブデザインの対応"
  - id: "TA19"
    name: "データベース設計"
    status: "in_progress"
    created_at: "2025-03-18"
    updated_at: "2025-03-18"
    parent: "TA17"
    description: "スキーマ設計とマイグレーション"
    concerns: "パフォーマンスチューニング"
